<?php
/**
 * Plugin Name: RSS Feed Icon for SpecificFeeds.com
 * Plugin URI: http://mycyberuniverse.com/my_programs/wp-plugin-specificfeeds-icon.html
 * Description: This plugin allows you to easily add RSS feed icon by SpecificFeeds.com in any place on your web-site.
 * Author: Arthur "Berserkr" Gareginyan
 * Author URI: http://mycyberuniverse.com/author.html
 * Version: 1.3
 * License: GPL3
 * Text Domain: specificfeedsicon
 * Domain Path: /languages/
 *
 * Copyright 2014-2015 Arthur "Berserkr" Gareginyan  (email : arthurgareginyan@gmail.com)
 *
 * This file is part of "RSS Feed Icon for SpecificFeeds.com".
 *
 * "RSS Feed Icon for SpecificFeeds.com" is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * "RSS Feed Icon for SpecificFeeds.com" is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with "RSS Feed Icon for SpecificFeeds.com".  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/**
 * Prevent Direct Access
 */
defined('ABSPATH') or die("Restricted access!");

/**
 * Register text domain
 *
 * @since 0.1
 */
function specificfeedsicon_textdomain() {
	load_plugin_textdomain( 'specificfeedsicon', false, dirname( plugin_basename( __FILE__ ) ) . '/languages/' );
}
add_action( 'init', 'specificfeedsicon_textdomain' );

/**
 * Print direct link to SpecificFeeds admin page
 *
 * Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the SpecificFeeds admin page
 *
 * @since  1.3
 * @param  array $links Array of links generated by WP in Plugin Admin page.
 * @return array        Array of links to be output on Plugin Admin page.
 */
function specificfeedsicon_settings_link( $links ) {
	$settings_page = '<a href="' . admin_url( 'options-general.php?page=specificfeeds-icon.php' ) .'">' . __( 'Settings', 'specificfeedsicon' ) . '</a>';
	array_unshift( $links, $settings_page );
	return $links;
}
$plugin = plugin_basename( __FILE__ );
add_filter( "plugin_action_links_$plugin", 'specificfeedsicon_settings_link' );

/**
 * Register "SpecificFeeds" submenu in "Settings" Admin Menu
 *
 * @since 1.3
 */
function specificfeedsicon_menu() {
	add_options_page('SpecificFeeds', 'SpecificFeeds', 'manage_options', 'specificfeeds-icon', 'specificfeedsicon_render_submenu_page');
}
add_action('admin_menu', 'specificfeedsicon_menu');

/**
 * Attach Settings Page
 *
 * @since 0.2
 */
require_once( plugin_dir_path( __FILE__ ) . 'inc/settings_page.php' );

/**
 * Enqueue the style sheet for setting's page
 *
 * @since 1.3
 */
function specificfeedsicon_enqueue_codemirror_scripts($hook) {

    // Return if the page is not a settings page of this plagin
    if ( 'settings_page_specificfeeds-icon' != $hook ) {
        return;
    }

    // Style sheet
    wp_enqueue_style('styles', plugin_dir_url(__FILE__) . 'inc/style.css');
}
add_action( 'admin_enqueue_scripts', 'specificfeedsicon_enqueue_codemirror_scripts' );

/**
 * Register settings
 *
 * @since 0.1
 */
function specificfeedsicon_register_settings() {
	register_setting( 'specificfeedsicon_settings_group', 'specificfeedsicon_link' );
	register_setting( 'specificfeedsicon_settings_group', 'specificfeedsicon_icon' );
}
add_action( 'admin_init', 'specificfeedsicon_register_settings' );

/**
 * ShortCode SpecificFeeds
 *
 * @since 1.1
 */
function specificfeedsicon_shortcode() {

    // Set variables
    $sf_link = get_option( 'specificfeedsicon_link' );
    $sf_icon = get_option( 'specificfeedsicon_icon' );
    $sf_icon_src = plugins_url( 'inc/icons/' . $sf_icon . '_one.png', __FILE__ );

	// Generating output code
	return '<a
				href="'.$sf_link.'"
				target="_blank"
				rel="nofollow"
    		>
    		<img
    			src="'.$sf_icon_src.'"
    			width="48"
    			height="48"
    			style="border: none;"
    		/>
    		</a>';
}
add_shortcode('specificfeeds-icon', 'specificfeedsicon_shortcode');

/**
 * Delete Options on Uninstall
 *
 * @since 0.1
 */
function specificfeedsicon_uninstall() {
	delete_option( 'specificfeedsicon_link' );
	delete_option( 'specificfeedsicon_icon' );
}
register_uninstall_hook( __FILE__, 'specificfeedsicon_uninstall' );

?>
