<?php
/**
 * Plugin Name: SpecificFeeds
 * Plugin URI:  ‎
 * Description: This plugin allows you to insert rss feed icon by SpecificFeeds.com in any widget area.
 * Author: Arthur "Berserkr" Gareginyan
 * Author URI: http://mycyberuniverse.com/author.html
 * Version: 1.0
 * License: GPL3
 * Text Domain: specificfeeds
 * Domain Path: /languages/
 *
 * Copyright 2014  Arthur "Berserkr" Gareginyan  (email : arthurgareginyan@gmail.com)
 *
 * This file is part of "SpecificFeeds".
 *
 * "SpecificFeeds" is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * "SpecificFeeds" is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with "SpecificFeeds".  If not, see <http://www.gnu.org/licenses/>.
 *
 */

defined('ABSPATH') or die("Restricted access!");

/**
 * Register text domain
 *
 * @since 0.1
 */
function specificfeeds_textdomain() {
	load_plugin_textdomain( 'specificfeeds', false, dirname( plugin_basename( __FILE__ ) ) . '/languages/' );
}
add_action( 'init', 'specificfeeds_textdomain' );

/**
 * Print direct link to SpecificFeeds admin page
 *
 * Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the SpecificFeeds admin page
 *
 * @since  0.1
 * @param  array $links Array of links generated by WP in Plugin Admin page.
 * @return array        Array of links to be output on Plugin Admin page.
 */
function specificfeeds_settings_link( $links ) {
	$settings_page = '<a href="' . admin_url( 'options-general.php?page=settings_page.php' ) .'">' . __( 'Settings', 'specificfeeds' ) . '</a>';
	array_unshift( $links, $settings_page );
	return $links;
}
$plugin = plugin_basename( __FILE__ );
add_filter( "plugin_action_links_$plugin", 'specificfeeds_settings_link' );

/**
 * Register "SpecificFeeds" submenu in "Settings" Admin Menu
 *
 * @since 0.1
 */
function specificfeeds_menu() {
	add_options_page('SpecificFeeds', 'SpecificFeeds', 'manage_options', 'settings_page.php', 'specificfeeds_render_submenu_page');
}
add_action('admin_menu', 'specificfeeds_menu');

/**
 * Attach Settings Page
 *
 * @since 0.2
 */
require_once( plugin_dir_path( __FILE__ ) . 'inc/settings_page.php' );

/**
 * Register settings
 *
 * @since 0.1
 */
function specificfeeds_register_settings() {
	register_setting( 'specificfeeds_settings_group', 'specificfeeds_link' );
	register_setting( 'specificfeeds_settings_group', 'specificfeeds_icon' );
}
add_action( 'admin_init', 'specificfeeds_register_settings' );

/**
 * ShortCode SpecificFeeds
 *
 * @since 1.0
 */
function specificfeeds_shortcode() {


    // Set variables
    $sf_link = get_option( 'specificfeeds_link' );
    $sf_icon = get_option( 'specificfeeds_icon' );
    
	// Generating output code
	return '<a
			href="'.$sf_link.'"
			target="_balnk"
			rel="nofollow"
    		>
    		<img
    			src="http://www.specificfeeds.com/theme/classic/img/publisher/download/'.$sf_icon.'_one.png"
    			width="48"
    			height="48"
    			style="border: none;"
    		/>
    		</a>';
}
add_shortcode('specificfeeds', 'specificfeeds_shortcode');

/**
 * Delete Options on Uninstall
 *
 * @since 0.1
 */
function specificfeeds_uninstall() {
	delete_option( 'specificfeeds_link' );
	delete_option( 'specificfeeds_icon' );
}
register_uninstall_hook( __FILE__, 'specificfeeds_uninstall' );


/* That's all folks! */
?>
