<?php

/**
 * Prevent Direct Access
 *
 * @since 0.1
 */
defined( 'ABSPATH' ) or die( "Restricted access!" );

/**
 * Register text domain
 *
 * @since 4.2
 */
function specificfeedsicon_textdomain() {
    load_plugin_textdomain( RFIFS_TEXT, false, RFIFS_DIR . '/languages/' );
}
add_action( 'init', RFIFS_PREFIX . '_textdomain' );

/**
 * Print direct link to plugin admin page
 *
 * Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the plugin admin page
 *
 * @since  4.2
 * @param  array $links Array of links generated by WP in Plugin Admin page.
 * @return array        Array of links to be output on Plugin Admin page.
 */
function specificfeedsicon_settings_link( $links ) {
    $page = '<a href="' . admin_url( 'options-general.php?page=' . RFIFS_SLUG . '.php' ) .'">' . __( 'Settings', RFIFS_TEXT ) . '</a>';
    array_unshift( $links, $page );
    return $links;
}
add_filter( 'plugin_action_links_' . RFIFS_BASE, RFIFS_PREFIX . '_settings_link' );

/**
 * Print additional links to plugin meta row
 *
 * @since 4.2
 */
function specificfeedsicon_plugin_row_meta( $links, $file ) {

    if ( strpos( $file, RFIFS_SLUG . '.php' ) !== false ) {

        $new_links = array(
                           'donate' => '<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=8A88KC7TFF6CS" target="_blank"><span class="dashicons dashicons-heart"></span> ' . __( 'Donate', RFIFS_TEXT ) . '</a>'
                           );
        $links = array_merge( $links, $new_links );
    }

    return $links;
}
add_filter( 'plugin_row_meta', RFIFS_PREFIX . '_plugin_row_meta', 10, 2 );

/**
 * Register plugin's submenu in the "Settings" Admin Menu
 *
 * @since 4.2
 */
function specificfeedsicon_register_submenu_page() {
    $menu_title = 'SpecificFeeds';
    $capability = 'manage_options';
    add_options_page( RFIFS_NAME, $menu_title, $capability, RFIFS_SLUG, RFIFS_PREFIX . '_render_submenu_page' );
}
add_action( 'admin_menu', RFIFS_PREFIX . '_register_submenu_page' );

/**
 * Register settings
 *
 * @since 4.2
 */
function specificfeedsicon_register_settings() {
    register_setting( RFIFS_SETTINGS . '_settings_group', RFIFS_SETTINGS . '_settings' );
    register_setting( RFIFS_SETTINGS . '_settings_group', RFIFS_SETTINGS . '_service_info' );
}
add_action( 'admin_init', RFIFS_PREFIX . '_register_settings' );
